baseURL = ""
languageCode = "en-us"
title = "My New Hugo Site"
theme = "coder"

defaultcontentlanguage = "en" # The default content language.

paginate = 10 # Default number of pages per page in pagination.

pygmentsstyle = "b2" # Color-theme or style for syntax highlighting.
pygmentscodefences = true # Enable code fence background highlighting.
pygmentscodefencesguesssyntax = true # Enable syntax guessing for code fences without specified language.
pygmentsUseClasses = true # new add

[params] # theme parameters
    author = "Aditya Sharma" # Author's name.
    info = "Aspiring ML engineer" # Author's job title or info.
    description = "Aditya Sharma's personal website" # Site description.
    keywords = "blog,developer,personal, portfolio, scientist, webspace" # Site keywords.
    avatarurl = "images/avi.jpg" # Contain the path of the optionnal avatar in the static folder.

    footercontent = "Made with &#9825; under &#9728; with lots of 🍉 " # Add footer content

